### ISSUE TITLE
the difference between fastq and channel?

### ISSUE THREAD

**Issue by FelixSeptem** [rfyiamcool/fastq#1]
I wanna to know the detail about the fastq and Golang builtin channel

**Comment by rfyiamcool** [comment]
@FelixSeptem 

lock free queue, reduce futex lock&release syscall by atomic, because go channel contains futex.

**Comment by FelixSeptem** [comment]
> @FelixSeptem
> 
> lock free queue, reduce futex lock&release syscall by atomic, because go channel contains futex.

thx for reply
